### PR TITLE
Pijs

### PR DESCRIPTION
**Pull request by ironbishop**
Request for inclusion of a new project.
Warning: must find and commit a logo before merging!

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hmmm – it doesn’t seem to really fit Libre Projects. @libreprojects/contributors what do you think?

**Comment by lucab** [comment]
I agree, this looks more like a web-app package intended for local installation.

**Comment by jancborchardt** [comment]
@ironbishop is it ok that I’m closing this? As we said above it seems really like something more local and not really for general web app use. I know the Libre Projects requirements are a bit strict but through that we get the best open source web apps which are useful for many people. :) (Cause there are so many!)

**Comment by ironbishop** [comment]
oknoprob :)

**Pull request closed without merging**
