### PR TITLE
New project: Taiga #128

### PR DESCRIPTION
**Pull request by Xaviju**
Project: Taiga
URL: https://taiga.io/
Source: https://github.com/taigaio
Description: Free. Open Source. Powerful. Taiga is a project management platform for startups and agile developers & designers who want a simple, beautiful tool that makes work truly enjoyable.

### CODE REVIEW

**Comment by yuwash** [comment]
Great! I haven’t checked out the project but it’s definitely highly interesting. Concerning the almost perfect commit:
- please put the logo (without changing its resolution) into the middle of a 160×160 canvas (resulting image in that size).
- I’m not completely sure if the "description" value of "project management" is short enough

**Comment by jancborchardt** [comment]
»projects« would be an apt shorter tag. :)

**Comment by Xaviju** [comment]
Thanks both! I updated it. :)
@yuwash we created an example project (The Princess Bride) if you want to check Taiga: https://tree.taiga.io/project/the-princess-bride/

**Comment by yuwash** [comment]
@Xaviju Thanks for the link; looking at that example, it looks really sophisticated, both regarding the breadth of features and maturity of each one. As an opensource Kanban implementation I haven’t seen any close to this.

I appreciate your very fast update, just concerning the logo, it seems to be a misunderstanding; You didn’t need to actually rescale it, but just add equal margins to the old 128×128 image to get 160×160. Look at [logos/imgbi.png](https://github.com/libreprojects/libreprojects/blob/gh-pages/logos/imgbi.png) for an example.

**Comment by Xaviju** [comment]
@yuwash updated again, sorry for the mistake. Hope it is fixed now.
Thanks for your kind words about taiga!

**Comment by yuwash** [comment]
Brilliant! I’d say :+1: ; Other @libreprojects/contributors ?

**Comment by jancborchardt** [comment]
The line break broke it, but I fixed that. Live at http://libreprojects.net :)

**Pull request merged**
