### PR TITLE
New project: img.bi #8 #issuecomment-33021458

### PR DESCRIPTION
**Pull request by yuwash**
- logo imgbi.png from https://github.com/imgbi , resized to 128×128 and changed canvas size (centered) to 160×160
- entry in data.json , introduction text from README file, license info from LICENSE file in imgbi/img.bi project

### CODE REVIEW

**Comment by ironbishop** [comment]
pushed i10n via yuwash/libreprojects#1

**Comment by jancborchardt** [comment]
@libreprojects/contributors what do you think?

**Comment by yuwash** [comment]
Thanks @ironbishop , this will be an high-quality entry! Just added German translation to do what I can.

**Comment by adelq** [comment]
LGTM

**Comment by jancborchardt** [comment]
Looks good as well. :)

**Pull request merged**
