### PR TITLE
Wallabag/Framabag

### PR DESCRIPTION
**Pull request by yuwash**
This replaces #81 as well as poche #77
rebased on the current gh-pages head

This pull request adds the new project [wallabag](https://github.com/wallabag/wallabag), formerly called poche, with a hosted instance at http://www.framabag.org

### CODE REVIEW

**Comment by jancborchardt** [comment]
As asked in #81, can you put it in one commit? It’s just 2 new lines and a new logo, so that’s easily done manually in a new branch off gh-pages. Otherwise our commit history and RSS feed is bunched up with merge and update commits. :)

**Comment by yuwash** [comment]
Sorry that I hadn't fully understood your intention last time. Maybe we need some kind of developer guide file with all the rules scattered around this project site.

Anyway, all the seven commits have been squashed into one now.

**Comment by jancborchardt** [comment]
@yuwash thanks!

@libreprojects/contributors @nicosomb what do you think? Looks good?

**Comment by jancborchardt** [comment]
And finally getting this in.

btw @yuwash since you are a member of the Libre Projects organization, you can also clone the main repository directly and make branches off that. That way, other Libre Projects members can collaborate on that branch (which is not possible when it’s a branch on your own fork).

**Comment by yuwash** [comment]
@jancborchardt that'd be nice, yes, I just didn't think about that, so I'll surely try that out next time.

**Pull request merged**
