### PR TITLE
New Project: graphhopper #83

### PR DESCRIPTION
**Pull request by yuwash**
- entry in js/data.json: introduction text and license info from https://github.com/graphhopper/graphhopper
- ~~logo combines (comparatively) high-res image header.png (cut out just the letter g) and the green background of favicon.ico, both from graphhopper.com, used lanczos interpolation and +70/127 contrast (gimp) (color,alpha) to enlarge it to the minimum acceptable size of 128×128~~

(it's still done the old way on my own fork because the commit was from the 6th March when the base version didn't match (now it can be merged, therefore this pull request) )

---

Edit:
- ~~logo uses header.png (cut out just the letter g), fit into the relative layout of favicon.ico, both from graphhopper.com, used lanczos interpolation and +70/127 contrast (gimp) (color,alpha) to enlarge it to the minimum acceptable size of 128×128~~
- deletes entry in js/data.json and logo of OpenRouteService

---

Edit:
- logo uses http://graphhopper.com/maps/img/icon.png , resized to 128×128 and put on 160×160 canvas

### CODE REVIEW

**Comment by jancborchardt** [comment]
So doesn’t this replace OpenRouteService? :)

**Comment by jancborchardt** [comment]
Oh and about the logo, I think it’s ok to simply use the g – just make it white. The green is a bit jarring and also doesn’t appear prominently on their page (or in their logo, except the favicon).

**Comment by yuwash** [comment]
Thanks for the comments. The “g” was and is still sub-optimal, but now the green background has been removed. OpenRouteService removed too.

**Comment by jancborchardt** [comment]
Here’s the high-resolution icon from their repo: https://github.com/graphhopper/graphhopper/blob/master/web/src/main/webapp/img/icon.png – there we could remove the green.

And another thing: Please put Graphhopper where OpenRouteService used to be, at the second spot (after OSM). Maps and routing should be directly next to each other. :)
And maybe we should cut the description to simply »routing« to keep it short.

**Comment by yuwash** [comment]
- That's nice! I should've found it before making that “g” image on my own. Now, however, when they are actually using it prominently in their github project, I'm not sure whether we should really remove the background just because “it fits better”. @karussell what do you think?
- I actually didn't understand why they were ordered that way. However, shouldn't graphhopper be sorted before openstreetmap in that case? (alphabetical within that “subcategory”) 
- I noticed openmarkers should also be removed

**Comment by karussell** [comment]
Hey, thanks for pinging me. I would prefer that you use the original logo (best if used and regularly updated from graphhopper.com) or a completely different one.

What I'm not sure is if GraphHopper service fits into the 'Libre Projects' as I do not currently allow free usage of the service (due to massive hardware requirements etc). Of course I would be happy if you include it as it is Open Source ..

**Comment by yuwash** [comment]
Thanks for the response! Do you mean the service available at http://graphhopper.com/maps/ is not identical to the opensource software? Anyway, we found that hosted service quite useful and nice, so we decided to include it.

Concerning the logo, you do not wish us to use the original [green-backed “g” logo found in your repository](https://github.com/graphhopper/graphhopper/blob/master/web/src/main/webapp/img/icon.png), but the full “graphhopper” logo used at graphhopper.com? As at our site, the logos have a limited quadratic space, I'd cut that long logo into “graph” and “hopper” in two lines, as we're doing for several other logos. Do you still prefer that from using your favicon design? (green-backed “g”) Or what else do you suggest?

**Comment by karussell** [comment]
> Do you mean the service available at http://graphhopper.com/maps/ is 
> not identical to the opensource software?

No this is identical but the underlying API (which is also Open Source) cannot freely be used from other web sites or products.

> but the full “graphhopper” logo used at graphhopper.com?

Sorry. I just mean the green logo which also available at graphhopper.com: http://graphhopper.com/maps/img/icon.png 

I will update this in the near future (slightly less agressive green ;)) but for now just use this, yes.

**Comment by jancborchardt** [comment]
I think it’s ok if the API is not free-of-cost – as long it’s open source and the website itself is free-of-cost to use (or has a free plan).

@yuwash the ordering is purely subjective, according to importance. Alphabetical order does not make much sense for a curated site. We want to showcase the best, or most relevant – they go first. OpenStreetMap naturally is the most important one. And as routing normally belongs to a maps app (but OpenStreetMap doesn’t have it …) we should put the service that does routing next.

@yuwash also good point about removing openmarkers because of deprecated domain. @libreprojects/contributors does someone want to prepare a pull request for that? It’s a good starting point if you want to get contributing. :)

**Comment by yuwash** [comment]
With d551bc1ecf52da2e1c3825afa713f45edc2c9025 (old commit replaced in order to keep rss uncluttered),
- the description is "routing",
- graphhopper is at the second place within category="travel"
- new logo from http://graphhopper.com/maps/img/icon.png is used

**Comment by jancborchardt** [comment]
Thank you @yuwash! :) Looks good to me.

@libreprojects/contributors what do you think?

**Comment by ironbishop** [comment]
Good.

**Comment by karussell** [comment]
Nice, thanks! How does search working? E.g. for 'maps', 'directions' or 'routing' GraphHopper does not show up on libreprojects.net

**Comment by ironbishop** [comment]
Search is based on project names only. Maybe we should add category?

**Comment by jancborchardt** [comment]
Yeah, good call. The category and the tags should be added as well. @karussell @ironbishop are you interested in adding that to the search?

**Comment by karussell** [comment]
Sorry, currently don't have enough time.

**Comment by ironbishop** [comment]
for reference, the search filter is [here](https://github.com/libreprojects/libreprojects/commit/bd2f073c1b5f833983d820e5f7dd0478086f872e#diff-7a0cec65d0998139bdbaa5c3fe761c5aR185)

**Pull request merged**
