### PR TITLE
Terms of Service; Didn't Read site address update

### PR DESCRIPTION
**Pull request by ktalik**
Website address has changed.

Cheers! :octocat:

### CODE REVIEW

**Comment by ironbishop** [comment]
Thanks

**Comment by jancborchardt** [comment]
Right, missed that. Thank you!

**Comment by ktalik** [comment]
I converted an issue to contribution opportunity :wink: You're welcome.

**Comment by jancborchardt** [comment]
@ktalik if there’s any more you want to contribute, you’re very welcome! :)

**Pull request merged**
