### PR TITLE
Wallabag

### PR DESCRIPTION
**Pull request by yuwash**
This replaces poche https://github.com/libreprojects/libreprojects/pull/77 , rebased on the commit 821f76fe3921f5d84b606acefcee01df935a67a3

The new project is at [wallabag/wallabag](https://github.com/wallabag/wallabag)

### CODE REVIEW

**Comment by jancborchardt** [comment]
We should probably wait for the new logo, as well as for the hosted instance at http://www.framabag.org/ to be up and running. :)

cc @nicosomb @vjousse

**Comment by yuwash** [comment]
The new logo is available now, so I've changed it. Framabag is also in my view “up and running” and also shows the new logo. The site design is not as sophisticated as http://wallabag.org , though. Why do you prefer that site?

**Comment by jancborchardt** [comment]
@yuwash yes, the design of http://www.wallabag.org/ is better from a visual point, but http://www.framabag.org is still a better product page:
- it has a screenshot so you quickly see how it looks
- you can really quickly log in or sign up
- the mobile apps are easier to find (though granted, the browser extensions aren’t)

@nicosomb @vjousse ^ some feedback about how to improve the interaction design of http://wallabag.org ;)

And Libre Projects is more about giving quick access to the actual hosted instance – rather than just linking to project pages.

**Comment by jancborchardt** [comment]
@yuwash 2 things left:
- [x] the logo needs to be square: just cut the »wallabag« text below the icon
- [ ] also needs to be smaller: 128px, like the others
- [ ] your pull request needs to be rebased against gh-pages to update it (or just simply fork it anew and apply your changes again – so that the bar here is green instead of grey) ;)

Thanks! :)

**Comment by yuwash** [comment]
The maximum logo size seems to be 160×160, so I shrinked it to this size (you can always make it smaller, but not bigger) (remove text → cut off bottom margin (no top margin ex., but preserving intentional right margin) → centralize in a quadratic canvas using original width → resize to 160)

The rebase made the tab “Files changed” somehow cluttered. Should I make a new pull request?

**Comment by nicosomb** [comment]
Thank you for the advices, I add them in my todolist.

**Comment by jancborchardt** [comment]
@yuwash oh yeah, maybe add a new fresh pull request with one commit. :) Thanks!

**Comment by nicosomb** [comment]
I just updated website: screenshots are available and mobile apps are downloadable on "downloads" page

**Pull request closed without merging**
