### PR TITLE
update ownCloud to Nextcloud

### PR DESCRIPTION
**Pull request by jancborchardt**
ownCloud was forked by the community to [Nextcloud](https://nextcloud.com). Please review @libreprojects/contributors @tcitworld

### CODE REVIEW

**Comment by tcitworld** [comment]
:+1:

**Comment by airon90** [comment]
Why ownCloud has been forked and why should we replace ownCloud with nextCloud?

**Comment by jancborchardt** [comment]
@Airon90 regarding the fork, read this [blog post by Frank](http://karlitschek.de/2016/04/big-changes-i-am-leaving-owncloud-inc-today/) and [watch the Q&A](https://www.youtube.com/watch?v=iMfokaX2r8g). :)

About why we’ll replace it, we clearly state in our goals:

> Not every project will be listed here […]. It’s not about giving many choices, it’s about providing the best solutions.

Since Nextcloud is the better, community-driven project, we will showcase that.

**Comment by yuwash** [comment]
That looks like a logical step. And the commit looks good. :+1:

**Pull request merged**
