### PR TITLE
Adjust header and search box to work on mobile. Closes #69

### LINKED ISSUE #69: make Search bar flow with header
Currently, on smaller resolutions, the search overlaps the page header. In order to make this theme mobile-friendly, need to redesign it a bit to allow it to flow under the header, or equivalent.

### PR DESCRIPTION
**Pull request by squareleaf**
Added a breakpoint, using mobile first and adding a breakpoint for greater
than 600px. This adds a colored background for region so it overlaps the
other text gracefully. Makes title text smaller and removes top margin.
Moves search box down and slides other content down accordingly.

Heard about your site via openhatch.org and saw this issue there. Let me know if there's anything special I need to do beyond a PR. Thanks!!

### CODE REVIEW

**Comment by ironbishop** [comment]
...I don't get it. http://it.tinypic.com/r/j627nl/5 
Maybe I did something wrong.

**Comment by jancborchardt** [comment]
@squareleaf thank you! Cool to hear you saw about Libre Projects via OpenHatch! :)
The pull request works good on mobile! Do you also want to adjust it so it works on tablets (/ slightly bigger sizes where the title and search box overlap), as @ironbishop mentioned?

**Comment by squareleaf** [comment]
A lot of tablets report their display size as being larger than it actually is. Do you have a size range in mind - perhaps 600px up to 750px?

**Comment by jancborchardt** [comment]
@squareleaf the overlap starts to happen at around 810px width (depending a bit on the typeface of course), so starting there would be good. And the lower end of the range would be at 600px where your breakpoint starts.

What do you think?

**Comment by jancborchardt** [comment]
@squareleaf if you fix that size range for tablets it’s good to merge from my side. :)

**Comment by squareleaf** [comment]
Sorry for the delay - life stuff has gotten in the way. I'll try to get to this in the next day or two. Thanks for the reminder.

**Comment by squareleaf** [comment]
Any changes to the PR? Tablet sizes are in the recent commit.

**Comment by jancborchardt** [comment]
@squareleaf oh sorry, didn’t see your commit after your comment! :)

@libreprojects/contributors can you folks test this pull request also? I’m busy at the moment but will check it tomorrow.

**Comment by jancborchardt** [comment]
@squareleaf thank you! :) I adjusted the styles a tiny bit after all. Btw is it ok if I add you to the http://github.com/libreprojects contributors group?

**Comment by squareleaf** [comment]
@jancborchardt Sure, that's fine. Thanks. :)

**Comment by jancborchardt** [comment]
@squareleaf and you’re added. :) If you switch it to public it will also be shown on your profile: https://github.com/orgs/libreprojects/members

**Pull request merged**
