### PR TITLE
Tweaking travel category

### PR DESCRIPTION
**Pull request by simison**
- Add nomadwiki.org and trashwiki.org
- Add info, tags and alternatives for many items under travel category

### CODE REVIEW

**Comment by simison** [comment]
Nomadwiki is sort of underground version of Wikivoyage. Wikivoyage has all these expensive hotels and restaurants listed, where as Nomadwiki is trying to have info only about free/cheap stuff (eg. free camping spots etc).

Trashwiki is a guide about dumpster diving.

**Comment by jancborchardt** [comment]
@simison thank you! Can you tweak the logos so they have the same visual weight as the other ones? (To preserve size, the logo part should usually be 128_128px. Then for example if the logo is square, like the Couchsurfing logo, and would look visually bigger than the others, add a bit whitespace around it to make it around 160_160px.)

Also, the Trashwiki logo needs a transparent background – best just take the default one and reverse the color from black to white so it’s visible. :)

**Comment by jancborchardt** [comment]
@simison because we merged https://github.com/libreprojects/libreprojects/pull/80 you need to rebase your pull request. – The issues are basically just that you need to take your version and add square brackets around the license info on the entries. Like `"licenses":["mit"]`

**Comment by jancborchardt** [comment]
Yo @simison, I found this PR again. :) Care to make the changes I mentioned above, then we can get this merged!

**Comment by ironbishop** [comment]
Closing for lack of interest.

**Pull request closed without merging**
