### PR TITLE
New project: inventaire #126

### PR DESCRIPTION
**Pull request by maxlath**

### CODE REVIEW

**Comment by jancborchardt** [comment]
I would maybe cut the description down to just »books« to keep it short and not overflowing. :) Otherwise it looks good.

What do you think @libreprojects/contributors?

**Comment by maxlath** [comment]
description shortened :)

**Comment by jancborchardt** [comment]
I like it :+1: – what do the other @libreprojects/contributors think?

**Comment by yuwash** [comment]
:+1: Perfect, I like the site, keep up the work!

**Comment by jancborchardt** [comment]
Cheers @maxlath :)

**Comment by maxlath** [comment]
whooho! thanks :D

**Pull request merged**
