### PR TITLE
Never show no search results

### LINKED ISSUE #15: never show no search results
The instant search should never show no results (also not a »no results« notification)

For example, if you want to search for »news« and then add a »a« by mistyping, »newa« will bring up no results. But there, the results of »new« should still show.

### PR DESCRIPTION
**Pull request by ironbishop**
I accidentally my previous pull request. fixes #15

### CODE REVIEW

**Comment by jancborchardt** [comment]
@jhuet can you review this?

We should also use a slight jQuery animation (collapse/expand or fade) to show/hide the elements. Now they just hide and show quickly which is very rogh.

**Comment by ironbishop** [comment]
@jancborchardt is this what you meant?

**Comment by jancborchardt** [comment]
@ironbishop hm, just checked it out and the animation seems to look weird more than it helps. It’s probably better without it after all.

@jhuet do you also want to check it out?

**Comment by jhuet** [comment]
Hi there, i gotta agree that the animation looks a bit overhead like that. Maybe if we really want one we could just to the animation on the categories once they are empty/not empty instead than on all items. It would be a bit more coding but might be worth a shot.

**Comment by jancborchardt** [comment]
Ok, i’d say we go for the simple solution first. :) @ironbishop can your remove the animation again? Sorry for the confusion. :)

**Comment by ironbishop** [comment]
is it ok now?

**Comment by jancborchardt** [comment]
@ironbishop yeah, thank you! I didn’t pull it in until now because I was on vacation and traveling the last 2 weeks. :)

**Comment by jancborchardt** [comment]
@ironbishop what would be cool additionally is a small note at the top before the results, similar to how Google does it. Saying `No results for »wikidot«, here are the results for »wiki« instead:`

**Comment by jancborchardt** [comment]
Is that possible? It’s good as feedback, because otherwise you’re not really sure if the search is broken (similar issue as before with no results, but the other way around kind of ;)

**Comment by ironbishop** [comment]
will work on it asap

**Comment by ironbishop** [comment]
see #51 @jancborchardt

**Pull request merged**
