### PR TITLE
removed echoplexus, added jitsi meet

### LINKED ISSUE #157: wire instead of echoplex
Echoplexus has been discontinued. (Mar 18, 2016)
It still works (I presume, still have to check). 

Should we list Wire instead? @libreprojects/contributors, what do you think?
Free as in Freedom :white_check_mark: 
Web-based & Hosted :white_check_mark: 

https://wire.com/
https://github.com/wireapp

### PR DESCRIPTION
**Pull request by ironbishop**
resolves #157

### CODE REVIEW

**Comment by yuwash** [comment]
That was fast, looks good 👍 Thanks

I’m not sure though if the [note](https://github.com/jitsi/jitsi-meet/blob/master/LICENSE) 

> This project was originally contributed to the community under the MIT license

constitutes an actual dual-licensing. (or perhaps it should be just apache)

**Comment by jancborchardt** [comment]
@yuwash MIT is compatible to Apache2: https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses – so it’s fine. :) The project is licensed under Apache2 now.

**Comment by jancborchardt** [comment]
Btw we’re now using Github’s review process – you can add reviewers in the top right, and review via there. :)

**Review by jancborchardt — APPROVED** [review]
Looks good! :)

**Comment by yuwash** [comment]
The compatibility goes only for converting MIT to Apache2 but not the other way around, so in my understanding the current version wouldn't be fully licensable as MIT

**Comment by jancborchardt** [comment]
Aaah right of course, didn’t see we have MIT listed there too. Of course, Jitsi is licensed Apache2 only. @ironbishop can you remove the MIT mention from the license block there? :)

**Comment by ironbishop** [comment]
yeah, ok. I'd commit directly to gh-pages, if you don't mind. Since it's a minimal difference, a PR seems superfluous.

**Comment by jancborchardt** [comment]
You can simply do it via direct editing on Github, that's faster  ut also creates a PR. :) I'd prefer for transparency if we simply do everything through PRs, and everyone sometimes makes mistaeks even in the smallest of changes. ;)

**Pull request merged**
