### PR TITLE
New project: Filestash #192

### PR DESCRIPTION
**Pull request by mickael-kerjean**
As per #192:

> @jancborchardt: I’d say if you like you can add it as per the guidelines at
> @ironbishop: It's a great project, seems ok to have it listed. +1

I tried to stick to the rules in the README. Although they weren't any clear alphabetical order, it did ended just before searx. Hope this is ok :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
> Although they weren't any clear alphabetical order, it did ended just before searx.

They are grouped by category. :) And in there ordered by how they will be listed. Searx should be first since it’s a search engine, very wide use. Makes most sense to put Filestash next to Nextcloud cause Nextcloud Files is similar. :)

**Comment by mickael-kerjean** [comment]
> Makes most sense to put Filestash next to Nextcloud

Done

> cause Nextcloud Files is similar. :)

Similar in a way but the scope and philosophy is quite different. Ultimately Filestash is a UI framework to build file manager type of UI (a good example of that is the LDAP backend: [example on a public LDAP server](https://demo.filestash.app/login?type=ldap&hostname=ldap%3A%2F%2Fipa.demo1.freeipa.org&bind_cn=uid%3Dadmin%2Ccn%3Dusers%2Ccn%3Daccounts%2Cdc%3Ddemo1%2Cdc%3Dfreeipa%2Cdc%3Dorg&bind_password=Secret123&base_dn=cn%3Daccounts%2Cdc%3Ddemo1%2Cdc%3Dfreeipa%2Cdc%3Dorg)).

Sure Filestash attaches itself to a range of backends (including Owncloud/Nextcloud via webDAV) but it's not a full blown solution with a suite of apps and tools, no storage, no sync tool and no authentication layer.

**Review by jancborchardt — APPROVED** [review]
Looks good! Another review @libreprojects/contributors? :)

**Review by lucab — APPROVED** [review]
LGTM

**Pull request merged**
