### PR TITLE
Add loomio to the projects

### LINKED ISSUE #90: Loomio
loomio.org

### PR DESCRIPTION
**Pull request by trolling42**
Since we have all the data available and I think loomio is under active development, I think loomio would be a good addition to the list. I want to resolve #90 with this pull request.

### CODE REVIEW

**Comment by yuwash** [comment]
Some issues:
- please use as license the existing name "gnu-agpl-v3", or create a new one if version is different (top of the data.json file)
- the logo should fit well in the quadratic form: it'd thus be better to just take the logo figure (i. e. without the word) and get a quadratic image with the logo figure in the center; take the existing logos as examples

Otherwise, it seems to be good

**Comment by trolling42** [comment]
Hi,
  I added the logo. Its not transparent. But, adding a transparent logo makes it look bad. It needs to be on an orange background. And also corrected the license.

**Comment by yuwash** [comment]
Nice, thanks, and yes, the logo is quite similar to those of the existing projects slid.es or libravatar, thus a quadratic background can/should be preserved when the logo is generally displayed that way e. g. on a picture, or the favicon is also designed that way etc.

I'm really glad that you're doing this, but just one detail I didn't mention above: logos like this (like libravatar) should have uniform margins: normally we do 128×128 in 160×160 canvas (so 16 px margins on each side) but I notice this logo is already smaller than that (96×96). I guess then 96×160÷128=120 should be the width of the new canvas.

Otherwise, :+1: What do some other @libreprojects/contributors say?

**Comment by airon90** [comment]
+1

**Comment by jancborchardt** [comment]
@charanlekkalapudi thank you! Can you adjust the canvas size to 120*120 px (leave transparent margins at the sides) as @yuwash mentioned?

**Comment by trolling42** [comment]
Hi Christoph,
   I'm not that familiar with graphic design. I will try to adjust, but it
would be nice if someone familiar would adjust that.

On Wednesday, March 26, 2014, Jan-Christoph Borchardt <
notifications@github.com> wrote:

> @charanlekkalapudi https://github.com/charanlekkalapudi thank you! Can
> you adjust the canvas size to 120*120 px (leave transparent margins at the
> sides) as @yuwash https://github.com/yuwash mentioned?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/libreprojects/libreprojects/pull/92#issuecomment-38715867
> .

## 

charan

**Comment by jancborchardt** [comment]
@charanlekkalapudi ok, I will do it. I also found a newer and better fitting logo.

**Comment by jancborchardt** [comment]
I added the logo: https://github.com/libreprojects/libreprojects/commit/c56ab3132d9a633a5fb7d2fdb1a509bfa0ed28eb and also changed the category to »organization« as well as shortened the description so it doesn’t overflow when you hover over the logo: https://github.com/libreprojects/libreprojects/commit/5beb33235136c48a601e332ac918fc99f400c80a

**Pull request merged**
