### PR TITLE
remove logos not used in data/json

### PR DESCRIPTION
**Pull request by yuwash**
just done:

```
for i in logos/*.png
do if ! echo "$i" | xargs basename | (read tt && grep -q "${tt%.png}" js/data.json)
then git rm "$i"
fi
done
```

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, good work! Just one point: https://play.freeciv.org is still there and open source, not sure why we removed it?

Do you want to re-add it to the data file? The rest is fine to be removed it seems.

**Comment by yuwash** [comment]
@jancborchardt It seems like you’ve removed it with 5cdfb291dd1e207a91c9f92adcb9c5604fce4ff3 because it is “old”? The link seems to be wrong there anyway. It was:

```
        {"id":"freeciv","category":"multiplayer","name":"Freeciv","description":"strategy","address":"http:\/\/freeciv.net\/"},
```

**Comment by jancborchardt** [comment]
Hmmm – I moved some games around there for some reason and must have forgot Freeciv. It still seems good, no? @yuwash if you like you can add it back again so we don’t miss it.

**Comment by yuwash** [comment]
@libreprojects/contributors Maybe you can take a look at the subsequent changes. Freeciv has been added (and its logo not removed).

**Comment by jancborchardt** [comment]
Looks good to me :+1: 

Other @libreprojects/contributors you wanna review too? :)

**Pull request merged**
