### PR TITLE
add project updates (changes to data.json) as feed, fix #27

### LINKED ISSUE #27: RSS Feed
It would be nice if there is an way to get informed about new projects.

### PR DESCRIPTION
**Pull request by jancborchardt**
A simple solution to have an RSS feed on the page. This just shows the changes to the data.json file, as @jhuet suggested in #27. I think that’s better because simpler than having additional overhead via hooks or building a custom feed.
As you see the commit messages should be properly worded sentences, but that should be the case always.

Please review @libreprojects/contributors!

### CODE REVIEW

**Comment by ironbishop** [comment]
:+1: ...I didn't see the single file feeds. That's better than hooking, and another good reason to write meaningful commit messages.

**Comment by jancborchardt** [comment]
Yeah, I didn’t know it was possible either. :) Looked around a bit, saw the »History« button and that’s that.

**Comment by jhuet** [comment]
Works, for me, thanks :)

**Comment by jancborchardt** [comment]
And now retweet it! :) https://twitter.com/jancborchardt/status/355725457250979843

**Pull request merged**
