### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ghost**
More W3C compliant and clearer

### CODE REVIEW

**Comment by yuwash** [comment]
:+1: Nice work. I just wait for some comments of others before merging to ensure there's no technical issue.

**Comment by jancborchardt** [comment]
Looking good, thank you @RyDroid ! :)
More improvements are always welcome, also check the discussions in the other issues.

**Comment by ironbishop** [comment]
As a side note, this broke some translation strings because that strings were wrong in the first place, so... time to fix translation :P ie, currently, it.json:24

**Comment by jancborchardt** [comment]
Oooh goood catch, crap I didn’t even notice that. It’s that loong string with lots of code. :O

**Pull request merged**
