### PR TITLE
Remove Transifex

### PR DESCRIPTION
**Pull request by strugee**
Transifex is proprietary since 2013.

### CODE REVIEW

**Comment by yuwash** [comment]
The logo could also be removed; Otherwise this is simple, thanks for the notice. Maybe as a replacement we could add [Zanata](http://zanata.org/) or [Weblate](https://hosted.weblate.org/)?

**Comment by jancborchardt** [comment]
Yeah, really unfortunate. :( We should indeed add a good replacement. Translatewiki isn’t really super awesome, eh?

**Comment by strugee** [comment]
@yuwash fixed in cd0cb82.

**Comment by yuwash** [comment]
Yeah, thanks, I’d say :+1: Otherwise, [translatewiki.net](https://translatewiki.net/) is a nice site to contribute to big projects as a translater, but your own small project will unlikely be included, so the purpose is a bit different from Transifex. Thus my favorite remains zanata.

**Comment by jancborchardt** [comment]
@strugee can you squash your commits into one to keep the history clean? :) Thanks!

**Comment by strugee** [comment]
@jancborchardt I'd be happy to, but as this is my first time ever squashing commits, I'm not sure exactly how to do it. Should I use `git rebase` to squash locally, and then force push to GitHub?

**Comment by strugee** [comment]
Also, I assume that you're asking me to squash so you can use the GitHub merge button, right? If so I'll point out that that creates an ugly merge commit anyway. I wish GitHub recognized rebases as merges...

**Comment by jancborchardt** [comment]
Fine like that, but next time it should be one commit. :)

**Comment by strugee** [comment]
@jancborchardt I was happy to squash, just wasn't sure exactly how :)

Anyway.

**Comment by jancborchardt** [comment]
@strugee cool, next time then. Don’t want to hold the development up too much. :)

For how to do a squash, see http://davidwalsh.name/squash-commits-git

**Pull request merged**
