### PR TITLE
Adding "Dotclear" project

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

### CODE REVIEW

**Comment by Jerome-Herbinet** [comment]
Also, can I have push access to upload Dotclear logo ?

**Comment by ironbishop** [comment]
is it an alternative to wordpress?

**Comment by Jerome-Herbinet** [comment]
> is it an alternative to wordpress?

Not completely. It's a simple blog CMS, simpler and lighter than WP.

**Comment by ccoenen** [comment]
Is there some kind of hosted version (since we're talking about WP anyway: something that would be similar to wordpress.com)?

**Comment by Jerome-Herbinet** [comment]
> Is there some kind of hosted version (since we're talking about WP anyway: something that would be similar to wordpress.com)?

Dotclear is self-hosted.

**Pull request closed without merging**
