### PR TITLE
Great change: new projects, new fields, new translation

### PR DESCRIPTION
**Pull request by airon90**
Hi you all,
I started editing data.json and I made some changes:
- I ordered the translations by code (de, en, eo, fr, it, ru)
- I ordered the licenses by id and added two licenses (CC BY 2.5 and The Gutenberg License)
- I ordered the alternatives by id and added some projects (Bit.ly, Google Documents, MATLAB, PayPal, Picasa, TinyUrl, Wolfram Alpha)
- I added a template in order to ease the add of new projects
- I ordered the projects by category and divided them by new lines
- Mailoo, Vanity (social), ur1.ca, BitCoin (tools), JSlander, Project Khalio, AncientBeast and Cobalt Calibur 3 (games) have been added (see [bug #19](https://github.com/libreprojects/libreprojects/issues/19))
- OpenPhoto has been replaced by PixlPaste (see [bug #30](https://github.com/libreprojects/libreprojects/issues/30))
- Wikitravel, a project bought by Internet Brands, has been replaced by Wikivoyage, a fork of Wikitravel maintained by Wikimedia Foundation
- I added to many projects all the parameters ("id", "category", "name", "description", "address", "licenses", "tags", "alternative", "introduction" and "source"). All parameters to all projects will be added later
- I changed the Esperanto translation
  What do you think? :)

### CODE REVIEW

**Comment by airon90** [comment]
@jancborchardt what do you think? A week passed and I'd like to continue adding data without closing and opening new issues... :/

**Comment by sindikat** [comment]
About Esperanto translation:
1. Typo in "malferMitkodaj", but i personally prefer to translate it as "liberaj", i.e. "free"
2. "FreedomBox" should be translated verbatim, as it is a brand.
3. Last names shouldn't be all-capitals, because this is an absolutely wrong and nonsensical tradition.
4. "plurpersonaj ludoj" is impractical, as on the website itself it will be too long to be visible under the icons; same with "risurcoj por edukado" and "listo de farendaĵoj"

**Comment by jancborchardt** [comment]
@Airon90 sorry, I was really busy and forgot to look at it. Will review it in a bit. @jhuet could you also check it out?

**Comment by airon90** [comment]
1. Free != Open source. I prefer "Free" instead of "Open source", too, but we have to ask @jancborchardt  and @jhuet if it is possible to change the sentence
2. No, "FreedomBox" should not be translated as it is a brand (I don't know why I translated it)
3. Is it a "non-sense tradition" or is it a rule? On the web, free software are translated by using this rule [1], in Wikipedia I don'tunderstand what they do [2].
4. Could you find another way to translate those terms without changing the meaning (multiplayer is not a web match, as it was translated before?

@jancborchardt Don't worry, I just wanted to know if you saw this req :)

[1] https://help.launchpad.net/Translations/GuidesList/Esperanto
[2] http://eo.wikipedia.org/wiki/Vikipedio:Baloto/Majuskligo_de_familiaj_nomoj

**Comment by jhuet** [comment]
@Airon90, i made a PR on your fork Airon90/libreprojects#1 with some corrections on the data.json that wasn't valid anymore. Accept it and it will automatically be added here.

We're also missing a lot of logo now :) If i remember correctly this is not something you're familiar with ?

As for the esperanto discussion i'll let you two decide as i have no knowledge in that language (unfortunatly).

**Comment by jhuet** [comment]
Oops, looks like you accepted your original PR too, thus putting everything live !

**Comment by airon90** [comment]
Sincerely I don't know what I did. You told me to accept and I accept the merge.
(it's the first time I work with merging code)
And now? :S

**Comment by jhuet** [comment]
Oh ok :) sorry i should have been more precise then. The PR i was talking was the one on your fork and should have been accepted there, not here. By accepting this one you put both mine and this one live.

I just reverted your merge so you're gonna have to open one again.

**Comment by jancborchardt** [comment]
@Airon90 no worries, those errors happen sometimes. That’s why we use git. :)

About the original pull request, here’s some review:
- translations order by code
  - I wouldn’t do that, because that’s the order they will show up in for the translation dropdown. Hence they should be ordered roughly by usage / target audience, for example: en, de, fr, ru, it, eo
- order licenses and add some
  - nice on the additions! The order here I’d not do alphabetically either, because some licenses like MIT, BSD and Apache clearly belong together because they are nearly the same.
- order alternatives and add some
  - also here great additions! And the order here is probably fine alphabetically.
- template to make adding projects easier
  - AWESOME!
- order projects by category and divided them by new lines
  - YEAH!
- Mailoo, Vanity (social), ur1.ca, BitCoin (tools), JSlander, Project Khalio, AncientBeast and Cobalt Calibur 3 (games) have been added (see [bug #19](https://github.com/libreprojects/libreprojects/issues/19))
  - Mailoo is cool!
  - Vanity is not hosted, you need a webhost of your own. Shouldn’t be added
  - ur1.ca doesn’t mention short link in any way and also short links are really bad for the web and make links look shady. The tool which needs short links is identica/statusnet, and they use ur1.ca by default. I’d say not add it.
  - Bitcoin is not hosted.
  - Project Khalio seems to be like a not-as-good-version of StillAlive JS (JS portal)
  - JSLander: the game is a bit boring honestly. We shouldn’t just add everything
  - Ancient Beast seems to be in pre-alpha stage, we should keep it in the backlog for now
  - Cobaltcalibour has wrong link, and the correct one can’t be loaded
- OpenPhoto replaced by PixlPaste
  - apparently https://openphoto.me has a free plan again. Also PixlPaste is not really a suitable replacement, it should rather be in »Tools« as »image sharing«. And OpenPhoto should be left in.
- Wikitravel, a project bought by Internet Brands, has been replaced by Wikivoyage, a fork of Wikitravel maintained by Wikimedia Foundation
  - NICE!
- I added to many projects all the parameters ("id", "category", "name", "description", "address", "licenses", "tags", "alternative", "introduction" and "source"). All parameters to all projects will be added later
  - great great great!
- I changed the Esperanto translation
  - no idea about that, but @sindikat apparently knows. :)

In general, all of these bullet points should be their own pull requests. That way it’s way easier to discuss them.
Thanks for the awesome work @Airon90!

**Comment by sindikat** [comment]
On Esperanto: i'm ok with @Airon90 decide.

**Comment by airon90** [comment]
We can discuss here about the first 5 points for the last two points and then for the addings and replacements I can open single commits, don't you? :)
Three notes:
- I thought Wikipedia style would be better instead of the old order (by usage), so that people can find more rapidly their own favourite language. If you want to keep the old order I delete this point from the pull req.
- I don't understand why @jancborchardt  says that «some licenses like MIT, BSD and Apache clearly belong together because they are nearly the same» so alphabetical order should be avoided. But I don't care about it, I just reorder all the entries in order to keep the code clear and not messy.
- I woud wait to merge esperanto translation because probably it will change with these future commits. I'd like know that there is [an open bug about it](https://github.com/libreprojects/libreprojects/issues/16). @sindikat  also said that some words (the long ones) would be displayed uncorrectly. What about it?

**Comment by jancborchardt** [comment]
@Airon90 ok, I don’t care particularly about license order, that can be alphabetical. Language order should be by use though – we don’t have that many languages yet so it’s better to order by usage.

Is that fine?

**Pull request merged**
