### PR TITLE
Removing Teamlab (no free hosting + apparent dead open source dev)

### PR DESCRIPTION
**Pull request by Reihar**
Removing Teamlab because there isn't a free hosting anymore plus open source dev seems dead

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Reihar Looks great! Good on putting in a blank line to separate the categories also. :)

Another reviewer please @libreprojects/contributors

**Comment by ironbishop** [comment]
:+1:

**Comment by jancborchardt** [comment]
Cool! Just to let you know, I think it’s good if we have an at-least-2-people-say-:+1: approach to pull requests. :) You can also merge it if you are the second one to say the pull is good.

**Comment by jancborchardt** [comment]
@Reihar thank you! You can close the issue then too. :)

**Pull request merged**
