### PR TITLE
Some details about Wikimedia projects

### PR DESCRIPTION
**Pull request by ironbishop**

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1: from me! Can we get another reviewer @libreprojects/contributors :)

**Comment by yuwash** [comment]
:+1:, no objections. How many languages you can speak!

10.06.2013, 12:54, "Jan-Christoph Borchardt" notifications@github.com:

**Comment by jancborchardt** [comment]
I guess Google Translate helped a bit. ;)

**Comment by ironbishop** [comment]
@jancborchardt nope, GT is not the source in this case! :) Each Wikimedia project is available in many languages, so I just copy/pasted from each homepage. Used GT indeed, only for double checking :P _Wikipedia is currently written in 284 languages._

**Comment by jancborchardt** [comment]
Aaah, right, that’s probably the best way to have it correct! :)

**Pull request merged**
