### PR TITLE
Add warning message to search

### PR DESCRIPTION
**Pull request by ironbishop**
Made l10n with Google Translate.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Oh nice! I like how you solved this in the interface, better than what I suggested!

Just some nitpicks:
- Instead of the "quotes", can you just put the term in strong tags? Then the text looks simpler.
- Also, the red looks a bit out of place. I’d make it just a bright grey, maybe #ccc.
- And just a little margin to the left so that it lines up with the text in the search box.
- If you type too much in the search box, the message makes the whole box move to the left. That could be solved just with overflow:hidden

**Comment by jancborchardt** [comment]
@ironbishop Nice! Much better. Just one more thing, when you type in a long word it will overflow to the right in the message. This can be fixed nicely by adding `overflow: hidden; text-overflow: ellipsis;` to #searchError. :)

**Comment by ironbishop** [comment]
@jancborchardt done... :pager:

**Comment by jancborchardt** [comment]
@ironbishop nice! (Btw, if you do the changes in a branch of the libreprojects repo instead, everyone here can make small changes themselves instead of needing to comment here. ;)

@libreprojects/contributors can we have another review? :)

**Comment by ironbishop** [comment]
ok then, I'll branch directly... and try not to break it :smile_cat:

**Comment by jancborchardt** [comment]
I just tested again and this seems good. :)

**Pull request merged**
