### PR TITLE
add Wikivoyage, remove Wikitravel

### LINKED ISSUE #40: Wikivoyage istead of Wikitravel
Wikitravel is a project bought by Internet Brands. So, I replaced it with Wikivoyage, a fork of Wikitravel maintained by Wikimedia Foundation.
It is added in my pull req.
Do we add it?

### PR DESCRIPTION
**Pull request by ironbishop**
to fix #40

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! cc @Airon90 

The only thing is that the new logo image is too big. To improve load times and because logos are not shown that big anyway, newly added ones should be 128_128 px. Can you change that? And also, the logo itself is just slightly too big when you compare it to the others. Inside that 128_128 px file, can you also reduce the size of the logo a bit so that it fits nicely with the others (probably just 10px less or so)?

**Comment by ironbishop** [comment]
@jancborchardt newbie question here: did i merge it right?

**Comment by jancborchardt** [comment]
@ironbishop hmm, I’m afraid it doesn’t really look right, because there are some changes unrelated to Wikivoyage in there. :\ Usually you don’t need to merge upstream in, only when similar lines of the same file were edited. I’m not sure how to clean it up either, maybe it’s best to issue a new pull request.

**Comment by ironbishop** [comment]
I messed up this PR, but apparently fixed the other :P

**Comment by jancborchardt** [comment]
@ironbishop wait, so which one was it? :)

**Comment by ironbishop** [comment]
PR #52 is still messed up, I will fix it in the near future
PR #51 is ok, I added a commit in response to your advices
:)

**Pull request closed without merging**
