### PR TITLE
Updates some CSS, header text overlapped icons

### PR DESCRIPTION
**Pull request by wrought**
also updates PLOS entry

### CODE REVIEW

**Comment by jancborchardt** [comment]
Wohooo! Thank you, looks good. Only one thing – because the title is so long already, it would be cool if you could cut the ending » (PLOS)« part from it.
(Btw, don’t know if you remember but we met last year in Oakland, I was with Rich Jones at sudoroom. :)

@libreprojects/contributors more reviewers?

**Comment by ironbishop** [comment]
+1 on both commit

**Comment by adelq** [comment]
Solves many visual glitches, very nice. +1

**Comment by wrought** [comment]
Hey @jancborchardt good to connect again, hope you are well!

Removed "(PLOS)" as requested. Thanks for the feedback all.

**Comment by jancborchardt** [comment]
Hm, strangely enough the CSS changes lead to the header links not working anymore. Not sure why, but you can’t click the category names anymore to link directly to one.

Any idea @wrought?

**Comment by wrought** [comment]
Hey, got the anchors working again. Going to add a couple of tickets, would like to get the search to be responsive, which currently overlaps the logo.

**Comment by jancborchardt** [comment]
Wohoo, nice! Also good on filing those other issues man!

**Pull request merged**
