### PR TITLE
wallabag changed it's licence a while ago

### PR DESCRIPTION
**Pull request by tcitworld**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Cool, thank you @tcitworld :)

(I wonder why it’s not AGPL, I have to say.)

**Comment by tcitworld** [comment]
Original creator has another opinion about freedom. Anyway.

**Comment by ironbishop** [comment]
still, that's an improvement from wtfpl... 

5/7, would merge :+1:

**Comment by jancborchardt** [comment]
> 5/7

@ironbishop :'D

**Pull request merged**
