### PR TITLE
New project: GNU social #135

### PR DESCRIPTION
**Pull request by benediktg**

### CODE REVIEW

**Comment by jancborchardt** [comment]
I checked the first GNU Social provider I got to from the landing page: https://loadaverage.org/main/all – it doesn’t look particularly awesome, and we already have Diaspora listed.

As we write in the [readme](https://github.com/libreprojects/libreprojects#libre-projects):

> Not every project will be listed here, especially not complicated ones. It’s not about giving many choices, it’s about providing the best solutions.

What do you think @libreprojects/contributors

**Comment by benediktg** [comment]
Gnusocial is in my opinion very easy to use – it does not differ much from Twitter in regards to usablity as I said. Did you also look at the other instances? There is a theme called "Qvitter" (https://github.com/hannesmannerheim/qvitter) available on some providers which "enhances" the similarity to Twitter (look for example at quitter.is, quitter.no or quitter.se). Since Gnusocial is implemented in PHP it should tend to be easier to set up and self-host than Diaspora.

After all I see no reason to doubt the relevance of it being in a listing of free (as in freedom) web services.

**Comment by benediktg** [comment]
I'm still waiting for an approval or refusal of the pull request – it's still mergable with one click. And if you reject the request I would like to read a rationale why you did so.

**Comment by jancborchardt** [comment]
Yo @libreprojects/contributors what do you think?

**Comment by yuwash** [comment]
The site gnu.io seems to be down right now, but anyway for consistency we should choose one instance rather than link to a list of instances. Concerning loadaverage.org, it seems to be stable and usable, but the lack of a link to any help/documentation might be an issue. (not even the name of the underlying software mentioned)

BTW for diaspora* perhaps we should link to a pod where one can actually create an account, because joindiaspora.com currently doesn’t allow to do so)

**Comment by benediktg** [comment]
It is wrong to just recommend one instance of a federated web service since it endangers the federation itself. On the gnu.io website (which is indeed not reachable right now) there is mentioned a small selection of hosted instances (which is okay as I think): https://web.archive.org/web/20150929140558/https://gnu.io/social/try/

And if you want to have a look at a more complete list of instances: http://www.skilledtests.com/wiki/List_of_Independent_Statusnet_Instances

**Comment by jancborchardt** [comment]
> It is wrong to just recommend one instance of a federated web service since it endangers the federation itself.

@benediktg we very clearly state in the readme:

> Not every project will be listed here, especially not complicated ones. It’s not about giving many choices, it’s about providing the best solutions.

We are trying to showcase open source projects which are awesome because of their great design and good functionality, not just because they go overboard with technical features. While federation is awesome, it’s a feature most normal people will not really see the immediate value in. The platform also needs to be well-designed. If it just looks like the CSS of Twitter did a few years ago (like some of the example installations of gnu.io) then how is it really better than Twitter for regular people?

Sorry that we’re so selective, but I think that is very important so that open source projects stay relevant among other well-designed web services. Gitlab, Piwik, ownCloud, Ghost and such are great examples of open source projects which are awesome not just because they are open source, but because they stack up really well to proprietary products in their field.

**Comment by yuwash** [comment]
As for the design, [Quitter.is](https://quitter.is/) really looks way better than loadaverage.org. IMO it can be considered quite mature and suitable for non-technical users given that it will stay online not just for a year like many instances do.

**Comment by jancborchardt** [comment]
For quitter.is specifically it looks like they just copied the CSS almost verbatim. And then also the name. That’s just not cool, and I don’t think we should promote that.

**Comment by wfdd** [comment]
They didn't 'copy' the name; it's just a pun.  Twitter; quit Twitter; qui-tter.  Quitter.  If people are quitting a proprietary service, they should be applauded.

If this project's simply about showcasing competitive open-source alternatives to proprietary software, with no regard for the ethics of software freedom, the use of terms like 'libre' and 'free software' is misleading.

**Comment by benediktg** [comment]
If you want to know more about GNU social, here is a nice summary: https://karp.id.au/social/user/index.html

**Comment by jancborchardt** [comment]
@benediktg now that Mastodon is pretty popular and very nicely usable, how about we change it to that? :)

**Comment by ironbishop** [comment]
Closing for lack of interest. If reopen, consider Mastodon.

**Pull request closed without merging**
