### PR TITLE
added Buddycloud

### PR DESCRIPTION
**Pull request by imaginator**
Logo next...

### CODE REVIEW

**Comment by jancborchardt** [comment]
Hmm – are you sure it’s »development« and not rather »social«? Because what you get is a communication platform after all.

cc @libreprojects/contributors

**Comment by imaginator** [comment]
Yes, we're focusing much more on building the tools and services that developers can then use to build open, federated messaging and services.

**Comment by yuwash** [comment]
I don't completely understand how it works, but it seems like it is a set of API that you use for your own project (frontend). How is that an alternative to google plus etc.? Does it offer a native web-based social coding platform? If there's some implementation that you can instantly use for communication that is based on Buddycloud, I think it'd better fit into libreprojects. Sorry if I've misunderstood something.

**Comment by imaginator** [comment]
Frontend and backend.
There are two demo clients http://demo.buddycloud.com/ (github.com/buddycloud/webclient) and the Android app https://github.com/buddycloud/buddycloud-android

I like the phrase "web based social coding platform" :) - the answer is Yes!

**Comment by yuwash** [comment]
What happened to this? The two commits for logo and `js/data.json` should be rather done in a single one, but otherwise this should be added!

**Comment by jancborchardt** [comment]
Closing because there seems to be no hosted service for end-users as it’s a developer tool. That’s cool, but Libre Projects is there to showcase end-user services. :)

**Pull request closed without merging**
