### PR TITLE
PR for #173: Drupal - correcting site & logo references

### PR DESCRIPTION
**Pull request by emjayess**
### PR Description copy/pasted from Issue #173 description:
---

Under **Publishing**, the _Drupal_ project links to – and uses a logo from – a now obsolete commercially hosted Drupal-as-a-service offering, then known as _Drupal Gardens_, and once hosted by Acquia (Drupal's flagship commercial entity, founded by Drupal project founder Dries Buytaert; but hardly the only entity offering commercial Drupal hosting services):

> drupal-gardens-incorrect

I'll submit a change/PR that updates the reference site/url to the project's _forever_ home, [Drupal.org](https://www.drupal.org/), alongside replacing the Drupal Gardens logo (which was only ever a logo for Acquia's commercial service, and is/was not the trademark logo for Drupal itself) with [Drupal's "druplicon" logo, from their official media kit](https://www.drupal.org/about/media-kit/logos):

> drupal-druplicon-correct

### CODE REVIEW

**Review by ironbishop — APPROVED** [review]
thank you @emjayess 

i would squash the commits into a single one, but I leave the final word to @jancborchardt

**Review by jancborchardt — COMMENTED** [review]
Just for the record: We deliberately chose Drupal Gardens cause it provided easy hosting/access, which Libre Projects is all about.

The Drupal project page itself has a subsite for that at https://www.drupal.org/hosting

**Comment by jancborchardt** [comment]
While that Drupal subsite is a bit hard to find, it probably still qualifies. :) So thanks for the change!

**Comment by jancborchardt** [comment]
And yeah, normally it should be one commit as @ironbishop said, but let's make it easy for first-time contributors to this repository. :)

**Comment by emjayess** [comment]
Thanks for accepting/merging :)

---

> And yeah, normally it should be one commit as @ironbishop said, but let's make it easy for first-time contributors to this repository. :)

@jancborchardt @ironbishop I'd have been happy to squash the commits for you – no stranger – I get _very_ granular with commits to my own projects, in this way, and only occasionally squash I guess; force of habit...

> Just for the record: We deliberately chose Drupal Gardens cause it provided easy hosting/access, which Libre Projects is all about.

and @jancborchardt I sort of figured that was the case, with originally directing to DrupalGardens. And I'm not even certain exactly when Acquia changed/pulled/rebranded that offering.

**Comment by jancborchardt** [comment]
@emjayess yeah, looking at your profile I expected you to be comfortable with squashing commits. It's just even more nice to not need to adjust anything though. :)
So, looking forward to more contributions from you! :tada:

**Pull request merged**
