### PR TITLE
+alphabetic order +identi.ca

### PR DESCRIPTION
**Pull request by airon90**
Fix issue #65

### CODE REVIEW

**Comment by ironbishop** [comment]
order is fine (see also https://github.com/libreprojects/libreprojects/pull/35#issuecomment-13034392), should identica now be removed from #10 ?

Also, we should write _user friendly_ commit messages, because of RSS (since #59).

**Comment by jancborchardt** [comment]
I’m fine with this as well. :)

Good point by @ironbishop – @Airon90 for future commits it would be cool to have a slightly more descriptive commit message. :)
Also, this should ideally have been two commits – one for the order, and one for adding identica.

**Comment by jancborchardt** [comment]
@ironbishop oh and no, identi.ca should not be removed from #10 – because that page lists other alternatives to the projects that we have on the site.

**Comment by ironbishop** [comment]
we just broke it @jancborchardt @Airon90 

**edit**: i pushed 015e89b because of this
**edit**: ...but it's still not going live...? :question:

**Comment by airon90** [comment]
Sincerely I don't know.
I forgot to add that I removed a "cpal-v1" in the license array because there is another "cpal-v1", but I don't think that this is an error.

@libreprojects/contributors I'm not able to do that, is it possible to revert and just to add identi.ca?

**Comment by ironbishop** [comment]
sigh... "_you need a verified email address to publish to page_" ...that's why my commit did not solve the issue! 

Site will be fixed at next push. **edit**: pushed 3aba7b7 and fixed.

**Comment by jancborchardt** [comment]
Thank you @ironbishop! :)

**Comment by airon90** [comment]
There's no identi.ca official logo.
What do we use? The pump.io one?

**Comment by jancborchardt** [comment]
Yeah, but there doesn’t seem a logo yet. Just asked Evan of pump.io about it: https://twitter.com/jancborchardt/status/436424895862681600

**Comment by yuwash** [comment]
pump.io doesn't have a logo image, but it's using a custom webfont “Arvo”, so you can make a screenshot of the letters “pump.io” displayed at their site.

**Comment by yuwash** [comment]
@jancborchardt said at #87:

> @yuwash as you said, the custom typeface thingy on their page is probably best. To have it not overly wide, only take the »pump« part.

I'm not sure if it's appropriate to strip the “.io” part, which is an IMO inseparable part of the project name.

**Comment by jancborchardt** [comment]
Ok, then put the io also on there, but on the line below. Otherwise it's just too wide and unreadable.

**Pull request merged**
