### PR TITLE
Pull req

### PR DESCRIPTION
**Pull request by airon90**
I reopen the pull request, because in the last one I did something wrong [1]

[1] https://github.com/libreprojects/libreprojects/pull/35

### CODE REVIEW

**Comment by airon90** [comment]
@sindikat  let's discuss here about Esperanto translation!

**Comment by jancborchardt** [comment]
@airon90 @sindikat any update on this? :)

**Comment by jancborchardt** [comment]
@Airon90 I don’t know Esperanto, but since this is just one string change, can you please rebase (so we can merge) and double check if it’s correct? @sindikat can you check it too?

**Comment by yuwash** [comment]
I suggest “<strong>malferm</strong>kodaj gastigitaj retservoj” Source: [eo:w:Malfermkoda programaro](https://eo.wikipedia.org/wiki/Malfermkoda_programaro)

**Comment by jancborchardt** [comment]
@Airon90 what do you think?

**Comment by airon90** [comment]
+1 @yuwash  :)

**Comment by jancborchardt** [comment]
@Airon90 can you then update the pull request? Best make a new one from current master because this can’t be automatically merged as it’s outdated. :)

**Comment by jancborchardt** [comment]
@Airon90 is this pull request still current? Can I help you in updating it? :)

**Comment by jancborchardt** [comment]
It was changed in the meantime to »liberaj servoj kaj alternativoj« so I’m closing this. :)

**Pull request closed without merging**
