### PR TITLE
Javascript (Enalbe-Disable) Message

### PR DESCRIPTION
**Pull request by rameardo**
this pull request should solve [this bug](https://github.com/libreprojects/libreprojects/issues/175).

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Ramear225 nice, good call! :) Could you also put the CSS in the css file instead of inline, and since it’s a design change also post a screenshot for easier review (and confirming it’s how you want it to look like)? Thanks!

@hex-m @libreprojects/contributors can you also review?

**Comment by rameardo** [comment]
I will definitely do, and I will also review the [hex-m], welcome and capacity

**Review by ironbishop — APPROVED** [review]
Checked, it works fine. The red rectangle is an eyesore, but that's a minor issue. :+1:

**Comment by jancborchardt** [comment]
@Ramear225 could you maybe change it to not have red background? It’s really difficult to read, as @ironbishop also said.

**Comment by jancborchardt** [comment]
@Ramear225 what happened? :) Do you want to open a new pull request with the changes, or do you need help?

**Comment by rameardo** [comment]
index html favs wikipedia joindiaspora-com nextcloud openstreetmap jamendo plos
i think it's done, please can you check it. if you have any qusition write here comment.

**Comment by jancborchardt** [comment]
@Ramear225 good stuff! :) Only 2 things left:

- Could you link to https://www.enable-javascript.com/ in the text? Just linkify the "please enable Javascript" text part
- Could you squash your commits into one? This makes the history more clean for better overview. :) See how to do this at https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by rameardo** [comment]
Hallo,
i think it's done, please can you check it.
Best Regards

**Comment by rameardo** [comment]
Hallo jancborchardt,
any update, task is done.

Best Regards.

**Comment by jancborchardt** [comment]
@Ramear225 sorry for the late reply! :slightly_smiling_face:  Could you still squash the commits into one as mentioned above?

> Could you squash your commits into one? This makes the history more clean for better overview. :) See how to do this at https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by ironbishop** [comment]
I squash-merged it directly, thanks Ramear225

**Comment by jancborchardt** [comment]
Thanks a lot @ironbishop! :slightly_smiling_face:  Sorry, am very busy with other projects atm. :\

And big thanks @Ramear225 for fixing this! :tada: Welcome to the team!

**Pull request merged**
